### ISSUE TITLE
FYI the guide also works with DietPi

### ISSUE THREAD

**Issue by xanoni** [keks24/raspberry-pi-luks#11]
See https://github.com/MichaIng/DietPi/issues/3377#issuecomment-896750673

**Comment by keks24** [comment]
Awesome!

Actually, this guide should also be generally applicable for image files with partition information. :)

I just added this [here](https://github.com/keks24/raspberry-pi-luks#introduction).

**Comment by xanoni** [comment]
Yes I would advertise this clearly ... it's a long guide that takes some time to follow properly, so we want to give people confidence that they're not wasting their time.
