### ISSUE TITLE
Debian bullseye missing `CRYPTSETUP=` in `/etc/cryptsetup-initramfs/conf-hook` 

### ISSUE THREAD

**Issue by xanoni** [keks24/raspberry-pi-luks#13]
I noticed that in bullseye, the file `/etc/cryptsetup-initramfs/conf-hook` no longer contains the `CRYPTSETUP="y"` line. Is it still needed?

**Comment by xanoni** [comment]
FYI, I kept it in the file for now. System booted fine after upgrade to bullseye. I haven't checked if it's truly required.

**Comment by xanoni** [comment]
Still no problems after several reboots. I consider the guide bullseye ready, just need to clarify what happened to the `CRYPTSETUP=X` line. I assume it's the standard now and no longer needs to be specified explicitly.

**Comment by keks24** [comment]
From `Raspberry Pi OS (Buster)` in `/etc/cryptsetup-initramfs/conf-hook`:

```no-highlight
#
# CRYPTSETUP: [ y | n ]
#
# [...]
# Note: Honoring this setting will be deprecated in the future.  Please
# uninstall the 'cryptsetup-initramfs' package if you don't want the
# cryptsetup initramfs integration.
#
```

So, it was already deprecated in `Buster` and then removed in `Bullseye`, which means, that installing the package `cryptsetup-initramfs` should be sufficient.

**Comment by xanoni** [comment]
cool, as expected then ... thank you
