### ISSUE TITLE
latest raspberry os version (bullseye) does not boot into initramfs

### ISSUE THREAD

**Issue by topuli** [keks24/raspberry-pi-luks#14]
to be clear, this is not a problem of this guide it is a problem that comes with the latest raspberry os version.
to boot into initramfs /boot/config.txt should contain dtoverlay=vc4-fkms-v3d instead of dtoverlay=vc4-kms-v3d

**Comment by keks24** [comment]
I think, you are talking about [this](https://github.com/keks24/raspberry-pi-luks/blob/master/boot/config.txt#L95) or [this line](https://github.com/keks24/raspberry-pi-luks/blob/master/boot/config.txt#L99), so it should be fine. :)
