### ISSUE TITLE
chroot: mount --bind-rslave

### ISSUE THREAD

**Issue by xanoni** [keks24/raspberry-pi-luks#3]
Hey Keks, quick question, shouldn't the command `mount --make-rslave "/dev/"` be `mount --make-rslave "/mnt/dev/"` instead? My `/dev/pts` always gets screwed up when I wind down the chroot, and I assume it's because of that.

**Comment by keks24** [comment]
Hi Xanoni,

good catch!

Yes, it should be `mount --make-rslave "/mnt/dev/"`

I wonder why this still worked on my `Banana Pi`...

I will update this, when I finally got time to migrate to my new internal infrastructure.

-Keks
