### ISSUE TITLE
Repacking the initramfs .... (debugging section)

### ISSUE THREAD

**Issue by xanoni** [keks24/raspberry-pi-luks#5]
Hey again, I saw your debugging section which introduces commands such as `lsinitramfs` and `unmkinitramfs`. Have you figured out, by any chance, how I can repack the initramfs after unpacking it with `unmkinitramfs`?

I tried this `find . 2>/dev/null | cpio --quiet --dereference -o -H newc | gzip -9 > /boot/initramfs.cpio.gz`, but the Pi no longer boots afterwards.

**Comment by xanoni** [comment]
(I assume it breaks because the command does not restore links properly... but not sure)

EDIT: oh, obviously I need to remove `--dereference` ... let's see if that helps

**Comment by keks24** [comment]
Hello. :)

Try using `find` with `null character` instead of `new lines`:

```bash
$ find . -print0 | cpio --null --create --verbose --format=newc | gzip --best > /boot/custom-initramfs.cpio.gz
```

Source: https://wiki.gentoo.org/wiki/Custom_Initramfs#Creating_a_separate_file

**Comment by xanoni** [comment]
I didn't get to test this ... I needed it because my system no longer booted and I felt that tweaking the initramfs would be faster than restoring my whole boot partition, but in the end I just `dd`'d over a /boot from a different Pi. Close.
