### ISSUE TITLE
Dropbear not responding

### ISSUE THREAD

**Issue by xanoni** [keks24/raspberry-pi-luks#6]
Hey Keks, have you run into the scenario where you could ping the Pi after booting it, but the dropbear just wouldn't respond? Want to make sure I'm not missing anything stupid before I waste more time. I don't have a screen to connect the Pi to, unfortunately.

```bash
# /etc/dropbear-initramfs/config
DROPBEAR_OPTIONS="-p 22222 -I 60 -sjk"
```

```bash
$ ping 192.168.23.23 -c1                                                                                                                                                              ~
PING 192.168.23.23 (192.168.23.23): 56 data bytes
64 bytes from 192.168.23.23: icmp_seq=0 ttl=64 time=0.426 ms

--- 192.168.23.23 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.426/0.426/0.426/0.000 ms

$ nc 192.168.23.23 22222                                                                                                                                                              ~
$

$ ssh 192.168.23.23 -p22222                                                                                                                                                       ~
ssh: connect to host 192.168.23.23 port 22222: Connection refused

$ nmap 192.168.23.23 -p22222,22 -Pn                                                                                                                                                   ~
Host discovery disabled (-Pn). All addresses will be marked 'up' and scan times will be slower.
Starting Nmap 7.91 ( https://nmap.org ) at 2021-07-13 00:20 EDT
Nmap scan report for 192.168.23.23
Host is up.

PORT      STATE    SERVICE
22/tcp    filtered ssh
22222/tcp filtered easyengine

Nmap done: 1 IP address (1 host up) scanned in 3.17 seconds
```

Thank you.

**Comment by keks24** [comment]
> Hey Keks, have you run into the scenario where you could ping the Pi after booting it, but the dropbear just wouldn't respond?

Yes, when I copied a faulty `RSA 8192` key with multiple spaces to `/etc/dropbear-initramfs/authorized_keys`.

> I don't have a screen to connect the Pi to, unfortunately.

A cable would be perfect for debugging purposes. :)

You can debug this, by going in to the `chroot environment` again and executing `dropbear` manually as William did in [this issue](https://github.com/keks24/raspberry-pi-luks/issues/1#issuecomment-827088902).

**Comment by xanoni** [comment]
That was actually my hypothesis, that the key is malformatted ... I was checking that as we "speak" ....

**Comment by keks24** [comment]
I also see this:

```bash
$ ssh 192.168.23.23 -p22222                                                                                                                                                       ~
```

It should be actually like this:

```bash
$ ssh root@192.168.23.23 -p22222
```

**Comment by xanoni** [comment]
Oh I have specified everything for this IP in my `.ssh/config`, so that's fine ... just added the `-p` for you ... okay so I tested it in the chroot and it failed because the folder "/etc/dropbear" didn't exist ... but that's in my /root partition, not in the /boot partition, so not sure if it's the reason?

(testing as we "speak")

**Comment by keks24** [comment]
> the folder "/etc/dropbear" didn't exist

This directory only exists in the `initramfs`.

You could `unarchive` the `initramfs` and `chroot` into it and then execute `dropbear` manually from there. Be aware, that you use `busybox` with `ash` for this:

```bash
$ chroot "<path_to_unarchived_initramfs>" /usr/bin/busybox sh
```

**Comment by xanoni** [comment]
Thank you, I chrooted into the unpacked initramfs and found the bug ...

```
$ vi "/etc/dropbear-initramfs/config"
$ DROPBEAR_OPTIONS="-p 22222 -I 60 -sjk -b etc/dropbear-initramfs/ssh_banner.net"
```
from the guide should change to
```
$ vi "/etc/dropbear-initramfs/config"
$ DROPBEAR_OPTIONS="-p 22222 -I 60 -sjk -b etc/dropbear/ssh_banner.net"
```

... it couldn't find the banner ... d'oh. 

Now you may ask why I didn't have the `-b` in my issue above. Well, it didn't work without, so I assume I also eliminated some other bug in the process ;-)

**Comment by keks24** [comment]
> ... it couldn't find the banner ... d'oh.

Ah, another good catch!

I think, I will adapt the hook script accordingly. This would avoid confusion.

Thanks for finding these little details!

**Comment by xanoni** [comment]
Little details that have kept me from completing this for a week haha ... but I see the login prompt now. Much wow.

**Comment by xanoni** [comment]
By the way, it's all up and running now. Thanks again for the help here.
