### ISSUE TITLE
cryptsetup failed, bad password or options?

### ISSUE THREAD

**Issue by xanoni** [keks24/raspberry-pi-luks#7]
Another one ... any ideas? I haven't really dug into it yet, but my current hypotheses:

1) related to the different cipher that I'm using (AES-XTS)
2) I use very intimidating passwords that sometimes break software (>300 characters)

```
Please unlock disk cryptroot:
cryptsetup: cryptsetup failed, bad password or options?
Please unlock disk cryptroot:
cryptsetup: cryptsetup failed, bad password or options?
```

EDIT: and yes I used the right password ;-)

**Comment by xanoni** [comment]
(Trying to open the volume from the initramfs chroot now ..)

**Comment by xanoni** [comment]
Nope, not that easy ...

```bash
/ # cryptsetup open /dev/sda2 foobar
Enter passphrase for /dev/sda2:
Cannot initialize device-mapper. Is dm_mod kernel module loaded?
Cannot use device foobar, name is invalid or still in use.
/ #
```

**Comment by keks24** [comment]
> 1. related to the different cipher that I'm using (AES-XTS)

This: Cannot initialize device-mapper. Is dm_mod kernel module loaded?

Look for `.ko` files.

> 2. I use very intimidating passwords that sometimes break software (>300 characters)

I am not sure, if that character length is even supported. I also never tried that.

I have to catch some sleep. I did an all-nighter and cannot think properly. I will think of solutions later on.

**Comment by xanoni** [comment]
> This: Cannot initialize device-mapper. Is dm_mod kernel module loaded?

Yes, it's in the archive and visible in `lsmod`.

> I am not sure, if that character length is even supported. I also never tried that.

LUKS supports up to ~500 characters. I think the ArchWiki said that. And I can unlock it just fine without the dropbear workflow.

Seems I need to try another password.

**Comment by xanoni** [comment]
That was it. I chose a password between 100 and 200 characters and now it unlocks.

**Comment by keks24** [comment]
> That was it. I chose a password between 100 and 200 characters and now it unlocks.

Having such long passwords is more than overkill.

I think, you may want to read something about password entropy:

https://keepass.info/help/kb/pw_quality_est.html
https://security.stackexchange.com/a/46675
https://www.pleacher.com/mp/mlessons/algebra/entropy.html

A password with `128 bit entropy` is more than enough.

Also, the password will be actually useless, if the encryption method is not secure enough. :)

**Comment by xanoni** [comment]
I understand it's overkill, but if software is properly implemented, it also doesn't cost anything. So why settle for less.
